name: Deploy to Server
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
#      - name: Check out Repo
#        uses: action/checkout@v3
      - name: Deploy to the server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 54.236.79.196
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/jordan.thebyrnefamily.ca
            git pull
              
